apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - soft
    - nfsvers=4.1
  nfs:
    path: /mnt/nfserver/sdss_config
    server: 10.202.17.133 
