apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: splunk
  name: splunksds
  labels:
    app: splunk
    role: splunksds
    tier: sds
spec:
  replicas: 6
  selector:
    matchLabels:
      app: splunk
      role: splunksds
      tier: sds
  template:
    metadata:
      labels:
        app: splunk
        role: splunksds
        tier: sds 
    spec:
      volumes:
       - name: nfs-appdata
         nfs: 
           server: 10.202.17.133 # Change this!
           path: /mnt/nfserver/sdss_appdata
       - name: nfs-config
         nfs: 
           server: 10.202.17.133 # Change this!
           path: /mnt/nfserver/sdss_config
      hostname: sds
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - sds.splunk.svc.cluster.local
      containers:
        - name: splunksds
          image: splunk/splunk:latest
          ports:
           - containerPort: 8089
             name: splunk
          volumeMounts:
           - name: nfs-appdata
             mountPath: /opt/splunk/etc/deployment-apps/
          volumeMounts:
           - name: nfs-config
             mountPath: /opt/splunk/etc/sdss_config/
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_ETC
              value: /opt/splunk/etc
            - name: SPLUNK_PASSWORD
              value: changeme123
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
