apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: splunk
  name: splunksds
  labels:
    app: splunk
    role: splunksds
    tier: sds
spec:
  replicas: 2
  selector:
    matchLabels:
      app: splunk
      role: splunksds
      tier: sds
  template:
    metadata:
      labels:
        app: splunk
        role: splunksds
        tier: sds 
    spec:
      volumes:
        - name: sdss-config
          persistentVolumeClaim:
             claimName: sdss-config
        - name: sdss-appdata
          persistentVolumeClaim:
             claimName: sdss-appdata
      hostname: sds
      containers:
        - name: splunksds
          image: splunk/splunk:latest
          ports:
           - containerPort: 8089
             name: splunk
          volumeMounts:
           - mountPath: /opt/splunk/etc/deployment-apps
             name: sdss-appdata
           - mountPath: /opt/splunk/etc/apps/sdss_config/
             name: sdss-config
          env:
            - name: SPLUNK_HOME
              value: /opt/splunk
            - name: SPLUNK_ETC
              value: /opt/splunk/etc
            - name: SPLUNK_PASSWORD
              value: changeme123
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
