apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdss-appdata
  namespace: splunk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfsever/sdss_appdata"
